export type Point2D = { x: number; y: number };
export type FootprintVertex = Point2D;
export type ApertureType = "window" | "door" | "sliding_door";
export type ApertureSpec = { id: string; type: ApertureType; wallIndex: number; leftOffsetM: number; widthM: number; heightM: number; sillHeightM: number };
export type WallFinishRatios = { facebrick_ratio: number; plaster_ratio: number };
export type WallGeometry = { wall_id: string; length_m: number; height_m: number; gross_area_sqm: number; apertures_area_sqm: number; net_area_sqm: number; finishes: WallFinishRatios };
export type LinearJoints = { ridges_lm: number; hips_lm: number; valleys_lm: number; parapets_lm: number };
export type RoofStructuralStyle = "gable" | "hip" | "flat";
export type RoofGeometry = { structural_style: RoofStructuralStyle; pitch_degrees: number; pitch_factor: number; overhang_m: number; surface_area_sqm: number; linear_joints: LinearJoints };
export type FootprintGeometry = { area_sqm: number; perimeter_lm: number; vertices: FootprintVertex[]; offset_vertices?: FootprintVertex[] };
export type BaseUnitGeometry = { footprint: FootprintGeometry; walls: WallGeometry[]; wall_height_m: number; net_plaster_area_sqm: number; net_wall_area_sqm: number; total_aperture_area_sqm: number; roof: RoofGeometry };
export type ServicesRequested = { waterproofing_membrane: boolean; alkali_primer: boolean; crack_remediation: boolean; acrylic_topcoat: boolean };
export type LaborParameters = { allocated_crew_size: 1 | 2 | 3 | 4; standard_shift_hours: number; blended_hourly_rate: number };
export type BaseUnitObject = { base_unit_id: string; project_reference: string; geometry: BaseUnitGeometry; services_requested: ServicesRequested; labor_parameters: LaborParameters; facade_plaster_ratio: number };
export type QuoteLineItemResult = {
  id: string;
  description: string;
  quantity: number;
  unit: string;
  cost_zar: number;
};
export type QuoteCalculationResult = {
  multiplier_count: number;
  aggregated: {
    net_plaster_area_sqm: number;
    net_wall_area_sqm: number;
    roof_surface_area_sqm: number;
    total_linear_joints_lm: number;
    total_labor_hours: number;
    crew_days: number;
  };
  line_items: QuoteLineItemResult[];
  base_cost_zar: number;
  profit_zar: number;
  total_quote_zar: number;
  profit_margin_pct: number;
};
export type FloorplanNode = { id: string; x: number; y: number };
export type WallOrientation = "east" | "south" | "west" | "north";
export type StartFacing = "east" | "south" | "west" | "north";
export type TurnDirection = "left" | "right";
export type WalkWallInput = { id: string; label: string; lengthM: number; turnAfter?: TurnDirection };
export type RidgeLine = { id: string; start: Point2D; end: Point2D; kind?: "ridge" | "hip" | "valley" };
export type ExportedAperture = ApertureSpec & { wall_label: string; area_sqm: number };
export type ExportedRidgeLine = RidgeLine & { label: string; length_m: number };
export type FloorplanExport = { version: 2; exported_at: string; project_reference: string; walk: { start_facing: StartFacing; inputs: WalkWallInput[]; segments: WallSegment[] }; footprint: { vertices: FootprintVertex[]; offset_vertices: FootprintVertex[]; area_sqm: number; perimeter_lm: number }; roof: { structural_style: RoofStructuralStyle; pitch_degrees: number; overhang_m: number; outline_vertices: FootprintVertex[]; ridge_lines: ExportedRidgeLine[]; drawn_ridge_length_lm: number; surface_area_sqm: number; linear_joints: LinearJoints }; wall_height_m: number; facade_plaster_ratio: number; walls: WallGeometry[]; quantities: { total_aperture_area_sqm: number; net_wall_area_sqm: number; net_plaster_area_sqm: number }; apertures: ExportedAperture[] };
export type FloorplanPhase = "walk" | "locked";
export type WallPreset = { id: string; label: string; lengthM: number };
export type WallSegment = { id: string; label: string; lengthM: number; startX: number; startY: number; orientation: WallOrientation };
export type FloorplanState = { nodes: FloorplanNode[]; closed: boolean; apertures: ApertureSpec[]; wallHeightM: number; roofStyle: RoofStructuralStyle; roofPitchDeg: number; roofOverhangM: number; facadePlasterRatio: number };
